---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-pihole
  namespace: external-dns
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgC2yn1lhA3NpEJPyeNysQ6Y+NGWKK3Y5Bzc5LPpDqmmojD3QZ4bI4/wHOYORgNGhErZoaHPkCOl7Edm1Kn+svXhUNwhFRfCc6UE3v4o6RsymL1z/5ah4zuipTIACQCXtrOHFnXY1e0i4/esR5RsDkMYVmrYBpQUM+45MCEQZHzUMO+/7C9Y/bVW6uJ8fsBSwAqex6UNwk8SEcYIJPVOT5KtIRkcQv0ZyG/RXPTF/kUg/bZNntg7ICLWywB7FHYoT4MvyQgN2iz4YLlJXf0DOnJ9V86n1Jxc3mOSZdNDylrrnE3J8r+91pumqJgMywEwBOIE6TaGeBfd+NiSuo62Lw6tm+eemK1lGU+BimElgtfS9q3yI0d1jhLf8LTfaFDd0yDUl6vMATuaGzKZy2om3/0IPDCGeMjfx7bG6L3V2rvPKkmb7RxKa8c5YW0zAOmKmZFCakUNhY1cn2dbC7aM7PN/IpPFg46CGV36ekqvAo/xT4OAssF5rqVyi4DoIRm6YeBo4bK0VafSN2z9bI9Mgz8SLSrHcHV1cbkmFBbggT+Tx0SStnjrgO5RznDQMCqYV/WDMFIxjtMtVsW9nChtm4GIB0O5Lb0JAHgKxGNHW04M2yH+VQeJrLCmB6iRKKzZsquK1B9qFHI1HikGd7yTMVEnahvUdJUbqi3bAjeEHwzK5eImdvO9V29QHAWU3cnw3HDcr9/EFgtwqspQLc6rVBYQtg==
  template:
    metadata:
      name: external-dns-pihole
      namespace: external-dns
